apiVersion: v1
kind: Service
metadata:
  name: gkemicroserv
spec:
  type: NodePort
  selector:
    app: firestore-be
  ports:
    - name: gke-firstore
      protocol: TCP
      targetPort: 4000
      port: 4000
